POST http://localhost:3000/produtos
Content-Type: application/json

{
    "nome": "batata",
    "preco": 1,
    "quantidade": 8
}

###

PUT http://localhost:3000/produtos/1
Content-Type: application/json

{
    "nome": "Feijão Preto",
    "preco": 1,
    "quantidade": 8
}

###

GET http://localhost:3000/produtos