POST http://localhost:3000/produtos
Content-Type: application/json

{
    "nome": "batata",
    "preco": 1,
    "quantidade": 8
}

###

PUT http://localhost:3000/produtos/1
Content-Type: application/json

{
    "nome": "Feijão Preto",
    "preco": 1,
    "quantidade": 8
}

###

GET http://localhost:3000/produtos

###

PATCH http://localhost:3000/produtos/1
Content-Type: application/json

{
    "quantidade": 50
}

###

PATCH http://localhost:3000/produtos/4/compra
Content-Type: application/json

{
    "valor": 5
}

###

PATCH http://localhost:3000/produtos/4/venda
Content-Type: application/json

{
    "valor": 3
}